config/routes.rb
Rails.application.routes.draw do

  namespace :pages do
    get 'obeya_skills'
    get 'index'
    get 'prices'
    get 'evolution'
    get 'competition'
    get 'obeya_global'
    get 'prototipe'

  end

  resources :teams do
    resources :targets, controller: 'teams/targets' do
      resources :problems, only: [:create], controller: 'teams/targets/problems'
      resources :commitments, only: [:create, :show], controller: 'teams/targets/commitments'
    end
  end

  resources :targets
  resources :problems

  resources :commitments do
    resources :tasks, only: [:new, :create, :destroy, :update], controller: 'commitments/tasks'
    member do
      patch :complete
    end
  end

  resources :tasks, only: [] do
    member do
      patch :done
    end
  end

  namespace :charts do
    get 'commitment-level'
    get 'commitment-status'
    get 'planning-level'
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }


  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :commitment
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:create]

  def create
    @task = Task.new(task_params)
    @task.commitment = Commitment.find(params[:commitment_id])
    respond_to do |format|
      if @task.save
        @commitment = @task.commitment
        format.html { redirect_to teams_path, notice: 'Commitment was successfully created'}
        format.json { render json: @task, status: :created, location: @commitment }
        format.js
      else
        format.html { redirect_to  teams_path, alert: 'Unprocessable entity'}
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
    set_progress
  end

  def destroy
    @task.destroy
    set_progress
  end

  def done
    if @task.done == false
      @task.update_attribute(:done, true)
    else
      @task.update_attribute(:done, false)
    end
    set_progress
  end

  private

  def set_progress
    @total_tasks = (@task.commitment.tasks.count.to_f).round(1)
    @total_tasks_done_true = (@task.commitment.tasks.where(done: true).count.to_f).round(1)
    @progress = ((@total_tasks_done_true/@total_tasks)*100).round(2)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_progress(commitment)
    (((commitment.tasks.where(done: true).count.to_f) / (commitment.tasks.count.to_f)).to_f)*100
  end

  def tasks_done(commitment)
    commitment.tasks.where(done:true).count
  end
end

app/views/tasks/_index.html.erb
<% @commitment.tasks.each do |task|%>
  <%= render partial: 'tasks/task', locals: { task: task } %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row" id="task-<%= task.id %>">
    <div class="form-group col">
        <span class="checklist-reorder">
            <i class="material-icons">reorder</i>
        </span>
        <div class="custom-control custom-checkbox col">
            <input type="checkbox" class="custom-control-input" id="checklist-item-<%= task.id %>" name="commitment[tasks]" value="<%= task.id %>" <%= "checked" if task.done %>>
            <label class="custom-control-label" for="checklist-item-<%= task.id %>"></label>
            <div>
                <input type="text" placeholder="Checklist item" value="<%= task.name %>" data-filter-by="value" />
                <div class="checklist-strikethrough"></div>
                <%= link_to 'delete', commitment_task_path(@commitment.id, task), method: :delete, remote: true %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/create.js.erb
$('#task-list').append("<%= j render partial: 'tasks/task', locals: { task: @task } %>")
$('#progress-values').html("<%= @total_tasks_done_true.round(0) %>" + " / " + "<%= @total_tasks.round(0) %>")
$('#task-progress').css({"width":"<%= @progress %>%"})

app/views/tasks/destroy.js.erb
$('#task #task-<%= @task.id %>').remove()
$('#progress-values').html("<%= @total_tasks_done_true.round(0) %>" + " / " + "<%= @total_tasks.round(0) %>")
$('#task-progress').css({"width":"<%= @progress %>%"})

app/views/tasks/done.js.erb
$('#progress-values').html("<%= @total_tasks_done_true.round(0) %>" + " / " + "<%= @total_tasks.round(0) %>")
$('#task-progress').css({"width":"<%= @progress %>%"})