config/routes.rb
Rails.application.routes.draw do

  namespace :pages do
    get 'obeya_skills'
    get 'index'
    get 'prices'
    get 'evolution'
    get 'competition'
    get 'obeya_global'
    get 'prototipe'

  end

  resources :teams do
    resources :targets, controller: 'teams/targets' do
      resources :problems, only: [:create], controller: 'teams/targets/problems'
      resources :commitments, only: [:create, :show], controller: 'teams/targets/commitments'
    end
  end

  resources :targets
  resources :problems

  resources :commitments do
    resources :tasks, only: [:new, :create, :destroy, :update], controller: 'commitments/tasks'
    member do
      patch :complete
    end
  end

  resources :tasks, only: [] do
    member do
      patch :done
    end
  end

  namespace :charts do
    get 'commitment-level'
    get 'commitment-status'
    get 'planning-level'
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }


  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_floating-tasks.html.erb
<div class="collapse sidebar-floating" id="floating-chat">
  <div class="sidebar-content">
    <div class="chat-module" data-filter-list="chat-module-body">
      <div class="chat-module-top">
        <form>
          <div class="input-group input-group-round">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">search</i>
              </span>
            </div>
            <input type="search" class="form-control filter-list-input" placeholder="Search task" aria-label="Search Chat" aria-describedby="search-chat">
          </div>
        </form>
        <div class="chat-module-body">
          <%= current_user.owner_commitments.where(closing_date: nil).order('due_date asc').each do |commitment|%>
            <div class="media chat-item">
              <div class="media-body">
                <div class="chat-item-title">
                  <span class="chat-item-author" data-filter-by="text"><%= commitment.action %></span>
                  <span data-filter-by="text"><%= distance_of_time_in_words(commitment.due_date, Time.now) if commitment.due_date.nil? == false %></span>
                </div>

                <div class="chat-item-body" data-filter-by="text">
                  <% commitment.tasks.where(done: false).each do |task| %>

                  <p><%= task.name %></p>
                  <% end %>
                </div>

              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="chat-module-bottom">
        <span class="badge badge-pill badge-primary">Primary</span>
<span class="badge badge-pill badge-secondary">Secondary</span>
<span class="badge badge-pill badge-success">Success</span>
<span class="badge badge-pill badge-danger">Danger</span>
<span class="badge badge-pill badge-warning">Warning</span>
<span class="badge badge-pill badge-info">Info</span>
<span class="badge badge-pill badge-light">Light</span>
<span class="badge badge-pill badge-dark">Dark</span>
        <h6> Backlog: <%= commitments_by(current_user, 0) %> Waiting: <%= commitments_by(current_user, 1) %> This Week: <%= commitments_by(current_user, 2) %> </h6>
        <!-- <form class="chat-form">
          <textarea class="form-control" placeholder="Type message" rows="1"></textarea>
          <div class="chat-form-buttons">
            <button type="button" class="btn btn-link">
              <i class="material-icons">tag_faces</i>
            </button>
            <div class="custom-file custom-file-naked">
              <input type="file" class="custom-file-input" id="customFile">
              <label class="custom-file-label" for="customFile">
                <i class="material-icons">attach_file</i>
              </label>
            </div>
          </div>
        </form> -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer-app.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark sticky-bottom">
  <a class="navbar-brand" style="border-style: 1px solid " href="#">Plan</a>
  <a class="navbar-brand" href="#">Do</a>
  <a class="navbar-brand" href="#">Check</a>
  <a class="navbar-brand" href="#">Act</a>
  <a class="navbar-brand" href="#">Menu</a>
</nav>

app/views/shared/_footer.html.erb
<footer class="container border-top">
  <br>
  <div class="row ">
    <div class="col-12 col-md">
      <%= image_tag 'logo-obeya.png', style:'width:45px', class:'mp-2 mt-2'%>
      <small class="d-block mt-1 text-muted">&copy; 2017-2018</small>
    </div>
    <div class="col-6 col-md mt-2">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
      </ul>
    </div>
    <div class="col-6 col-md mt-2">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md mt-2">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
    <br>
</footer>

app/views/shared/_navbar.html.erb
<div class="navtop">
  <div class="navbar navbar-expand-lg bg-light navbar-light sticky-top">

    <a class="navbar-brand new" href="index.html">
      <%= image_tag 'logo-obeya.png', class:'logo'%>
    </a>
    <div class="d-flex align-items-center">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag 'burger.svg', class: 'logo burger' %>
      </button>

    </div>
    <div class="collapse navbar-collapse justify-content-between" id="navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', pages_index_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" id="nav-dropdown-2">Obeya<sup>&#174;</sup></a>
            <div class="dropdown-menu" aria-labelledby="nav-dropdown-2">
              <%= link_to 'Evolution', pages_evolution_path, class:'dropdown-item'%>
              <%= link_to 'Paradigms', pages_index_path, class:'dropdown-item'%>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" id="nav-dropdown-3">Impact</a>
            <div class="dropdown-menu" aria-labelledby="nav-dropdown-3">
              <a class="dropdown-item" href="components-pipeline.html">Teleworking</a>
              <a class="dropdown-item" href="components-pipeline.html">Allignment</a>
              <a class="dropdown-item" href="components-pipeline.html">Commitment</a>
              <a class="dropdown-item" href="components-pipeline.html">Morale</a>
              <a class="dropdown-item" href="components-pipeline.html">Safety</a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Prices', pages_prices_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="documentation/changelog.html">Contact</a>
        </li>
        <li class="nav-item">
          <%= link_to  pages_obeya_global_path, class:"btn btn-primary" do %>
          Obeya Global<sup>TM</sup>
          <% end %>
        </li>
      </ul>
      <div class="d-lg-flex align-items-center">
        <!-- <form class="form-inline my-lg-0 my-2">
          <div class="input-group input-group-light input-group-round">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">search</i>
              </span>
            </div>
            <input type="search" class="form-control form-control-light" placeholder="Search" aria-label="Search app" aria-describedby="search-app">
          </div>
        </form> -->
        <% if user_signed_in? %>
        <div class="dropdown ml-3">
          <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name %>

              <%= image_tag user_avatar(current_user.id), class:'avatar' %>


          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="burger-profile">
              <%= link_to 'My Obeya', teams_path , class:'dropdown-item' %>
              <%= link_to 'Account Settings', edit_user_registration_path, class:'dropdown-item' %>
              <%= link_to 'Log out', destroy_user_session_path, class:'dropdown-item', method: :DELETE %>
            </div>
          </div>
        </div>
        <div class="d-none d-lg-block">

        </div>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class:'btn btn-outline-primary ml-3' %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navside.html.erb
<div class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top">
  <a class="navbar-brand" href="index.html">
    <%= image_tag 'logo-obeya.png', style:"width:55px"%>
  </a>
  <div class="d-flex align-items-center">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-block d-lg-none ml-2">
      <div class="dropdown">

        <div class="dropdown-menu dropdown-menu-right">
          <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag user_avatar(current_user.id), class:'avatar' %>
          </a>
          <%= link_to 'Profile', teams_path , class:'dropdown-item' %>
          <%= link_to 'Account Settings', edit_user_registration_path, class:'dropdown-item' %>
          <%= link_to 'Log out', destroy_user_session_path, class:'dropdown-item', method: :DELETE %>
        </div>
      </div>
    </div>
  </div>
  <div class="collapse navbar-collapse flex-column" id="navbar-collapse">
    <ul class="navbar-nav d-lg-block">
      <li class="nav-item">
        <a class="nav-link" href="<%= pages_obeya_skills_path %>" >Obeya Skills</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1" aria-controls="submenu-1">Plan</a>
        <div id="submenu-1" class="collapse">
          <ul class="nav nav-small flex-column">
            <li class="nav-item">
              <a class="nav-link" href="<%= teams_path %>">Teams</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= targets_url(tab: "my-targets") %>">Targets</a>
            </li>
          </ul>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-2" aria-controls="submenu-2">Do</a>
        <div id="submenu-2" class="collapse">
          <ul class="nav nav-small flex-column">
            <li class="nav-item">
              <a class="nav-link m-1" href="<%= commitments_path(tab: "other-commitments") %>">Commitments</a>
            </li>
          </ul>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-3" aria-controls="submenu-3">Check</a>
        <div id="submenu-3" class="collapse">
          <ul class="nav nav-small flex-column">
            <li class="nav-item">
              <a class="nav-link ml-1" href="<%= problems_path %>">Problems</a>
            </li>
          </ul>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-4" aria-controls="submenu-4">Act</a>
        <div id="submenu-4" class="collapse">
          <ul class="nav nav-small flex-column">
            <li class="nav-item">
              <a class="nav-link ml-1" href="components-bootstrap.html">Action Plans</a>
            </li>

          </ul>
        </div>
      </li>

    </ul>
    <hr>
    <div class="d-none d-lg-block w-100">
      <span class="text-small text-muted">Quick Links</span>
      <ul class="nav nav-small flex-column mt-2">
        <li class="nav-item">
          <a href="#" class="nav-link">Matrix HK</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Kanban Board</a>
        </li>
      </ul>
      <hr>
    </div>
    <div>
      <form>
        <div class="input-group input-group-dark input-group-round">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="material-icons">search</i>
            </span>
          </div>
          <input type="search" class="form-control form-control-dark" placeholder="Search" aria-label="Search app" aria-describedby="search-app">
        </div>
      </form>
      <div class="dropdown mt-2">
        <button class="btn btn-primary btn-block dropdown-toggle" type="button" id="newContentButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Add New
        </button>
        <div class="dropdown-menu" aria-labelledby="newContentButton">
          <%= button_to 'Team', new_team_path, remote: true, class:'dropdown-item', data: {toggle:'modal', target:'#team-add-modal'}%>
          <%= button_to 'Target', targets_path, remote: true, class:'dropdown-item', data: {toggle:'modal', target:'#target-add-modal'} %>
          <%= button_to 'Commitment', commitments_path, remote: true, class:'dropdown-item', data: {toggle:'modal', target:'#commitment-add-modal'} %>
          <%= button_to 'Problem', commitments_path, remote: true, class:'dropdown-item', data: {toggle:'modal', target:'#commitment-add-modal'} %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-none d-lg-block">
    <div class="dropup">
      <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag user_avatar(current_user.id), class:'avatar' %>
      </a>
        <%= current_user.first_name %>
      <div class="dropdown-menu">
        <%= link_to 'My Obeya', teams_path , class:'dropdown-item' %>
        <%= link_to 'Account Settings', edit_user_registration_path, class:'dropdown-item' %>
        <%= link_to 'Log out', destroy_user_session_path, class:'dropdown-item', method: :DELETE %>
      </div>
    </div>
  </div>
</div>

<button class="btn btn-primary btn-round btn-floating btn-lg" type="button" data-toggle="collapse" data-target="#floating-chat" aria-expanded="false" aria-controls="sidebar-floating-chat">
  <i class="material-icons">check</i>
  <i class="material-icons">close</i>
</button>

<%= render 'shared/floating-tasks'%>
<%= render 'teams/new' %>
<%= render 'targets/new' %>
<%= render 'commitments/new' %>

app/views/shared/_navtop.html.erb
<div class="layout layout-nav-top">
  <div class="navbar navbar-expand-lg bg-light navbar-light sticky-top">
    <a class="navbar-brand" href="index.html">
      <img alt="Pipeline" src="assets/img/logo-obeya.png" class="" style="width:45px"/>
    </a>
    <div class="d-flex align-items-center">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="d-block d-lg-none ml-2">
        <div class="dropdown">
          <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="nav-side-user.html" class="dropdown-item">Profile</a>
            <a href="utility-account-settings.html" class="dropdown-item">Account Settings</a>
            <a href="#" class="dropdown-item">Log Out</a>
          </div>
        </div>
      </div>
    </div>
    <div class="collapse navbar-collapse justify-content-between" id="navbar-collapse">
      <ul class="navbar-nav">

        <li class="nav-item">

          <a class="nav-link" href="index.html">Home</a>

        </li>

        <li class="nav-item">

          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" id="nav-dropdown-2">Why Obeya?</a>
            <div class="dropdown-menu" aria-labelledby="nav-dropdown-2">

              <a class="dropdown-item" href="pages-app.html">App Pages</a>

              <a class="dropdown-item" href="pages-utility.html">Utility Pages</a>

              <a class="dropdown-item" href="pages-layouts.html">Layouts</a>

            </div>
          </div>

        </li>

        <li class="nav-item">

          <div class="dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" id="nav-dropdown-3">Impact</a>
            <div class="dropdown-menu" aria-labelledby="nav-dropdown-3">

              <a class="dropdown-item" href="components-bootstrap.html">Delivery</a>

              <a class="dropdown-item" href="components-pipeline.html">Cost</a>

              <a class="dropdown-item" href="components-pipeline.html">Quality</a>

              <a class="dropdown-item" href="components-pipeline.html">Morale</a>

              <a class="dropdown-item" href="components-pipeline.html">Safety</a>

            </div>
          </div>

        </li>

        <li class="nav-item">

          <a class="nav-link" href="documentation/index.html">Prices</a>

        </li>

        <li class="nav-item">

          <a class="nav-link" href="documentation/changelog.html">Contact</a>

        </li>

      </ul>
      <div class="d-lg-flex align-items-center">
        <form class="form-inline my-lg-0 my-2">
          <div class="input-group input-group-dark input-group-round">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">search</i>
              </span>
            </div>
            <input type="search" class="form-control form-control-dark" placeholder="Search" aria-label="Search app" aria-describedby="search-app">
          </div>
        </form>
        <div class="dropdown mx-lg-2">
          <button class="btn btn-primary btn-block dropdown-toggle" type="button" id="newContentButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Obeya
          </button>
          <div class="dropdown-menu" aria-labelledby="newContentButton">
            <a class="dropdown-item" href="#">Team</a>
            <a class="dropdown-item" href="#">Project</a>
            <a class="dropdown-item" href="#">Task</a>
          </div>
        </div>
        <div class="d-none d-lg-block">
          <div class="dropdown">
            <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img alt="Image" src="assets/img/avatar-male-4.jpg" class="avatar" />
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="nav-side-user.html" class="dropdown-item">Profile</a>
              <a href="utility-account-settings.html" class="dropdown-item">Account Settings</a>
              <a href="#" class="dropdown-item">Log Out</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main-container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-11">
          <section class="pt-4 pt-lg-5">
            <div class="row">
              <div class="col-md-6">

                <img alt="Pipeline" src="assets/img/recurso1.png" class="mb-3" style="width:80%"/>

              </div>

              <div class="col-md-6 justify-content-between">
                <h3 class="mb-1" style=" font-family:'merriweather' ">Obeya</h3>
                <h1 class="display-3 mb-3"> Unlocking Potential </h1>
                <p class="lead">
                  The first step-by-step application based on Lean Toyota to continuously improve your business performance
                </p>
                <button class="btn btn-lg btn-success" type="button" id="newContentButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Take a tour
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>

    <div class="jumbotron">
      <div class="container">
        <div class="row justify-content-center">
          <center>
            <h1>Simple rules for a complex world</h1>
            <p class="lead"> Make teams productive never was so easy Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
          </center>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-11">
          <section>
            <div class="row">

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>

              <div class="col-md-6">
                <div class="card mb-3">
                  <a href="nav-side-team.html">

                  </a>
                  <div class="card-body">
                    <a class="card-title h6" href="nav-side-team.html">Team</a>
                  </div>
                </div>
              </div>


            </div>
          </section>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/shared/_notices.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_user-invitation.html.erb
<form class="modal fade" id="user-invite-modal" tabindex="-1" role="dialog" aria-labelledby="user-invite-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Invite Users</h5>
        <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
      </div>
      <!--end of modal head-->
      <div class="modal-body">
        <p>Send an invite link via email to add members to this team</p>
        <div>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">email</i>
              </span>
            </div>
            <input type="email" class="form-control" placeholder="Recipient email address" aria-label="Recipient email address" aria-describedby="recipient-email-address">
          </div>
          <div class="text-right text-small mt-2">
            <a href="#" role="button">Add another recipient</a>
          </div>
        </div>
      </div>
      <!--end of modal body-->
      <div class="modal-footer">
        <button role="button" class="btn btn-primary" type="submit">
          Invite users
        </button>
      </div>
    </div>
  </div>
</form>

app/views/shared/_user_invitation.html.erb
<form class="modal fade" id="user-invite-modal" tabindex="-1" role="dialog" aria-labelledby="user-invite-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Invite Users</h5>
        <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
      </div>
      <!--end of modal head-->
      <div class="modal-body">
        <p>Send an invite link via email to add members to this team</p>
        <div>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">email</i>
              </span>
            </div>
            <input type="email" class="form-control" placeholder="Recipient email address" aria-label="Recipient email address" aria-describedby="recipient-email-address">
          </div>
          <div class="text-right text-small mt-2">
            <a href="#" role="button">Add another recipient</a>
          </div>
        </div>
      </div>
      <!--end of modal body-->
      <div class="modal-footer">
        <button role="button" class="btn btn-primary" type="submit">
          Invite users
        </button>
      </div>
    </div>
  </div>
</form>