config/routes.rb
Rails.application.routes.draw do

  namespace :pages do
    get 'obeya_skills'
    get 'index'
    get 'prices'
    get 'evolution'
    get 'competition'
    get 'obeya_global'
    get 'prototipe'

  end

  resources :teams do
    resources :targets, controller: 'teams/targets' do
      resources :problems, only: [:create], controller: 'teams/targets/problems'
      resources :commitments, only: [:create, :show], controller: 'teams/targets/commitments'
    end
  end

  resources :targets
  resources :problems

  resources :commitments do
    resources :tasks, only: [:new, :create, :destroy, :update], controller: 'commitments/tasks'
    member do
      patch :complete
    end
  end

  resources :tasks, only: [] do
    member do
      patch :done
    end
  end

  namespace :charts do
    get 'commitment-level'
    get 'commitment-status'
    get 'planning-level'
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }


  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_navside.html.erb
<div class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top">
    <a class="navbar-brand" href="index.html">
        <%= image_tag 'logo-obeya.png', style:"width:55px"%>
    </a>
    <div class="d-flex align-items-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-block d-lg-none ml-2">
            <div class="dropdown">
                <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img alt="Image" src="assets/img/avatar-male-4.jpg" class="avatar" />
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to 'Profile', teams_path , class:'dropdown-item' %>
                  <%= link_to 'Account Settings', edit_user_registration_path, class:'dropdown-item' %>
                  <%= link_to 'Log out', destroy_user_session_path, class:'dropdown-item', method: :DELETE %>
                </div>
            </div>
        </div>
    </div>
    <div class="collapse navbar-collapse flex-column" id="navbar-collapse">
        <ul class="navbar-nav d-lg-block">

            <li class="nav-item">


            </li>

            <li class="nav-item">

                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-2" aria-controls="submenu-2">Plan</a>
                <div id="submenu-2" class="collapse">
                    <ul class="nav nav-small flex-column">

                        <li class="nav-item">
                            <a class="nav-link" href="pages-app.html">Innovation Portfolio</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="pages-utility.html">Objetives</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="pages-layouts.html">Targets</a>
                        </li>

                    </ul>
                </div>

            </li>

            <li class="nav-item">

                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-3" aria-controls="submenu-3">Do</a>
                <div id="submenu-3" class="collapse">
                    <ul class="nav nav-small flex-column">

                        <li class="nav-item">
                            <a class="nav-link" href="components-bootstrap.html">Kanban Board</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="components-pipeline.html">Pipeline</a>
                        </li>

                    </ul>
                </div>

            </li>

            <li class="nav-item">

                <a class="nav-link" href="documentation/index.html">Check</a>

            </li>

            <li class="nav-item">

                <a class="nav-link" href="documentation/changelog.html">Act</a>

            </li>

        </ul>
        <hr>
        <div class="d-none d-lg-block w-100">
            <span class="text-small text-muted">Quick Links</span>
            <ul class="nav nav-small flex-column mt-2">
                <li class="nav-item">
                    <a href="nav-side-team.html" class="nav-link">Obeya Overview</a>
                </li>
                <li class="nav-item">
                    <a href="nav-side-project.html" class="nav-link">Obeya</a>
                </li>
                <li class="nav-item">
                    <a href="nav-side-task.html" class="nav-link">Commitments</a>
                </li>
                <li class="nav-item">
                    <a href="nav-side-kanban-board.html" class="nav-link">Kanban Board</a>
                </li>
            </ul>
            <hr>
        </div>
        <div>
            <form>
                <div class="input-group input-group-dark input-group-round">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="material-icons">search</i>
                        </span>
                    </div>
                    <input type="search" class="form-control form-control-dark" placeholder="Search" aria-label="Search app" aria-describedby="search-app">
                </div>
            </form>
            <!-- <div class="dropdown mt-2">
                <button class="btn btn-primary btn-block dropdown-toggle" type="button" id="newContentButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Add New
                </button>
                <div class="dropdown-menu" aria-labelledby="newContentButton">
                    <a class="dropdown-item" href="#">Team</a>
                    <a class="dropdown-item" href="#">Project</a>
                    <a class="dropdown-item" href="#">Task</a>
                </div>
            </div> -->
        </div>
    </div>
    <div class="d-none d-lg-block">
        <div class="dropup">
            <a href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag user_avatar(current_user.id), class:'avatar' %>

            </a>
            <%= current_user.first_name %>
            <div class="dropdown-menu">
              <%= link_to 'My Obeya', teams_path , class:'dropdown-item' %>
              <%= link_to 'Account Settings', edit_user_registration_path, class:'dropdown-item' %>
              <%= link_to 'Log out', destroy_user_session_path, class:'dropdown-item', method: :DELETE %>
            </div>
        </div>
    </div>
</div>

app/views/pages/certification.html.erb
<div class="layout layout-nav-top">
  <%= render 'shared/navbar' %>
  <div class="main-container">
    <div class="container">
      <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Certification<sup>TM</sup> Program</h1>
        <p class="lead">Enroll now to access a  </p>
      </div>
      <div class="container">
        <div class="card-deck mb-3 text-center">

          <div class="card mb-4 shadow-sm">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Trainee</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">US 300 <small class="text-muted">/ person</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Focus: Do/Check</li>
                <li>5S</li>
                <li>Estandarization of Work</li>
                <li>Commitemnt Management</li>
              </ul>
              <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
            </div>
          </div>
          <div class="card mb-4 shadow-sm">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Coach</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$8 <small class="text-muted">/ mo</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Focus: Act</li>
                <li>Kaizen</li>
                <li>Coaching Process</li>
                <li>Obeya Skills Development</li>
              </ul>
              <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
            </div>
          </div>
          <div class="card mb-4 shadow-sm">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Mentor</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>Focus: Plan</li>
                <li>Hoshin Kanri</li>
                <li>Mentoring Process</li>
                <li>Innovation Portofolio</li>
              </ul>
              <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
            </div>
          </div>
        </div>
      </div>
        </div>
          </div>
            <%= render 'shared/footer'%>
    </div>

    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>

app/views/pages/index.html.erb
<div class="layout layout-nav-top">
  <%= render 'shared/navbar' %>
  <div class="index">
  <div class="main-container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-11">
          <section class="pt-4 pt-lg-5">
            <div class="row text-center">
              <div class="col-md-6 align-items-center">
                <%= image_tag 'happyman.svg', style:'width:80%', class:'mb-3'%>
              </div>
              <div class="col-md-6 text-left">
                <div class="row">
                  <div class="col-md-12">
                    <h3 class="mb-1" style=" font-family:'merriweather' ">Obeya<sup>&#174;</sup></h3>
                    <h1 class="display-3 mb-3"> Unlocking Potential </h1>
                    <p class="lead">
                      The first step-by-step application based on Lean Toyota to continuously improve your business performance
                    </p>
                    <button class="btn btn-lg btn-success" type="button" id="newContentButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      Take a tour Now
                    </button>
                  </div>
                  <div class="col-md-12">
                    <small>Don't have an account yet? <%= link_to 'Create one', new_user_registration_path %></small>
                  </div>
                </div>

              </div>
            </div>
          </section>
          <div class="row">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="index">
    <div class="jumbotron">
      <div class="container text-center" >
        <h1>Lean Management Revolution</h1>

        <section class="pt-4 pb-4 pt-lg-5 card bg-light">
          <div class="row align-items-center">
            <div class="offset-md-2 col-md-4 text-center pb-4">
              <h3 class=""> PDCA Cycle </h3>
              <p class="lead white">
                The secret of Toyota's success is based on the continuous improvement, the PDCA cycle
                <span class="badge badge-secondary green-100">Plan</span>
                <span class="badge badge-secondary green-75">Do</span>
                <span class="badge badge-secondary green-50">Check</span>
                <span class="badge badge-secondary green-25">Act</span>
              </p>
            </div>
            <div class="col-md-4">
              <%= image_tag 'pdca_1.svg', style:'width:80%' %>
            </div>
          </div>
        </section>
        <section class="pt-4 pb-4 pt-lg-5 card bg-light">
          <div class="row align-items-center">
            <div class="offset-md-2 col-md-4 text-center pb-4">
              <h3 class=""> Obeya Room </h3>
              <p class="lead">
                Toyota made visible the process of continuous improvement using a big room - in japanese Obeya -.
              </p>
            </div>
            <div class="col-md-4">
              <%= image_tag 'obeyaroom.svg', style:'width:80%'%>
            </div>
          </div>
        </section>
        <section class="pt-4 pb-4 pt-lg-5 card bg-light">
          <div class="row align-items-center">
            <div class="offset-md-2 col-md-4 text-center pb-4">
              <h3 class=""> Obeya Board </h3>
              <p class="lead">
                Big companies are using Obeya boards to make visible the process of problem detection and act with speed
              </p>
            </div>
            <div class="col-md-4">
              <%= image_tag 'obeyaboard.svg', style:'width:80%'%>
            </div>
          </div>
        </section>
        <section class="pt-4 pb-4 pt-lg-5 mb-3 card bg-light">
          <div class="row align-items-center">
            <div class="offset-md-2 col-md-4 text-center pb-4">
              <h3 class=""> Obeya App</h3>
              <p class="lead">
                And now we want to put the process of continuous improvement in your hands to take action anytime and anywhere
              </p>
            </div>
            <div class="col-md-4">
              <%= image_tag 'obeyaapp.svg',style:'width:20rem'%>
            </div>
          </div>
        </section>
      </div>
    <%= image_tag 'phone.svg', style: 'width:100%', class:'text-right'%>
    </div>
  </div>

  <div class="index">
    <div class="jumbotron">
      <div class="container">
        <div class="container text-center mb-4">
          <h1 class="display-4">Impact</h1>
          <p class="lead">A business by definition creates results, Obeya by definition is the way to reach them</p>
        </div>
        <div class="case-studies">
          <div class="row justify-content-center">
            <div class="col-md-8 text-center">
              <h4><%= link_to 'Production', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Services', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Board Directors', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Costumer Services', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Human Resources', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Sales', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Marketing', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Finances', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Logistics', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Quality', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'Development', pages_index_path, class:'btn btn-dark mb-1' %></h4>
              <h4><%= link_to 'IT Support', pages_index_path, class:'btn btn-dark mb-1' %></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer'%>

app/views/pages/obeya_global.html.erb
<div class="layout layout-nav-top">
  <%= render 'navbar' %>
  <div class="index">
  <div class="main-container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-11">
          <section class="pt-4 pt-lg-5">
            <div class="row">
              <div class="col-md-12 mb-5">
                <h3 class="mb-1 title">Obeya Global<sup>&#174;</sup></h3>
                <h1 class="display-3"> Democratizing Consulting </h1>
                <p class="lead">
                  Anyone can be a consultant, front-line workers know the problems, costumers need to solve them
                </p>
                <%= link_to pages_obeya_global_path, class:"btn btn-primary" do %>
                Learn more
                <% end %>
              </div>
              <div class="col-md-4">
                <div class="card">
                  <div class="card-body">
                    <%= image_tag 'obeyaapp.svg', class:'mb-3' %>
                    <h4 class="card-title">Obeya Digital</h4>
                    <p class="card-text">Work with a native management platform and show us what you can do</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card">
                  <div class="card-body">
                    <%= image_tag 'obeyaapp.svg', class:'mb-3' %>
                    <h4 class="card-title">Obeya Academy</h4>
                    <p class="card-text">Pass the certification process to be able as trainee, coach or mentor</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card">
                  <div class="card-body">
                    <%= image_tag 'obeyaapp.svg', class:'mb-3' %>
                    <h4 class="card-title">Obeya Work</h4>
                    <p class="card-text">Access to our data-base with thousands of different costumer needs</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>
  <%= render 'footer'%>
</div>

app/views/pages/obeya_skills.html.erb
<div class="layout layout-nav-side">
  <%= render 'shared/navside' %>
  <div class="main-container">
    <div class="navbar bg-white breadcrumb-bar">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="<%= teams_path(tab: '#teams') %>">Overview</a>
          </li>
          <li class="breadcrumb-item active">
            <a> Obeya Skills </a>
          </li>

        </ol>
      </nav>

      <div class="dropdown">
        <button class="btn btn-round" role="button" data-toggle="dropdown" aria-expanded="false">
          <i class="material-icons">settings</i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">

          <a class="dropdown-item" href="#">Account Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger" href="#">Log out</a>

        </div>
      </div>

    </div>
    <%= render 'shared/notices'%>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-11 col-xl-10">
          <div class="page-header mb-4">
            <div class="media">
              <div class="media-body">
                <h1 class="mb-0">Obeya Skills</h1>
                <p class="lead">Welcome <%= current_user.first_name %>, here we are some skills to develop</p>
              </div>
            </div>
          </div>
          <ul class="nav nav-tabs nav-fill">
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#plan" role="tab" aria-controls="plan" aria-selected="false">Plan</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#do" role="tab" aria-controls="do" aria-selected="false">Do</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#check" role="tab" aria-controls="check" aria-selected="false">Check</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#act" role="tab" aria-controls="act" aria-selected="false">Act</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane fade active show <%= @tab == "plan" ? "active" : "" %>" id="plan" role="tabpanel" aria-labelledby="plan-tab" data-filter-list="content-list-body">
              <div class="row">
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <center><h6>Commitment Level Evolution</h6></center>
                        </a>
                      </div>
                        <%= area_chart  charts_commitment_level_path, xtitle: 'Weeks', ytitle: 'Commitment Level' %>
                    </div>
                  </div>

                </div>

              </div>

              <div class="row">
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="dropdown card-options">
                        <button class="btn-options" type="button" id="kanban-dropdown-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="material-icons">more_vert</i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="#">Edit</a>
                          <a class="dropdown-item text-danger" href="#">Archive Card</a>
                        </div>
                      </div>
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Planning Level</h6>
                        </a>
                      </div>
                      <ul class="avatars">
                        <li>
                          <a href="#" data-toggle="tooltip" title="David">
                            <h1 style="margin:0px"><%= level_of_planification(current_user)%>%</h1>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="dropdown card-options">
                        <button class="btn-options" type="button" id="kanban-dropdown-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="material-icons">more_vert</i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="#">Edit</a>
                          <a class="dropdown-item text-danger" href="#">Archive Card</a>
                        </div>
                      </div>
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Commitment Level</h6>
                        </a>
                      </div>
                      <ul class="avatars">
                        <li>
                          <a href="#" data-toggle="tooltip" title="David">
                            <h1 style="margin:0px"><%= level_of_commitment(current_user)%>%</h1>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="dropdown card-options">
                        <button class="btn-options" type="button" id="kanban-dropdown-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="material-icons">more_vert</i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="#">Edit</a>
                          <a class="dropdown-item text-danger" href="#">Archive Card</a>
                        </div>
                      </div>
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Fullfillment Level</h6>
                        </a>
                      </div>
                      <ul class="avatars">
                        <li>
                          <a href="#" data-toggle="tooltip" title="David">
                            <h1 style="margin:0px"><%= level_of_fullfillment(current_user)%>%</h1>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="dropdown card-options">
                        <button class="btn-options" type="button" id="kanban-dropdown-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="material-icons">more_vert</i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="#">Edit</a>
                          <a class="dropdown-item text-danger" href="#">Archive Card</a>
                        </div>
                      </div>
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Resolution Level</h6>
                        </a>
                      </div>
                      <ul class="avatars">
                        <li>
                          <a href="#" data-toggle="tooltip" title="David">
                            <h1 style="margin:0px"><%= resolution(current_user).round(0)%> days</h1>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Mini kanban Board</h6>
                        </a>
                      </div>
                        <table class="table">
                          <thead>
                            <tr>
                              <th scope="col">Status</th>
                              <th scope="col">You</th>
                              <th scope="col">Team</th>
                              <th scope="col">% Desv</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <th scope="row">Backlog</th>
                              <td><%= commitments_by(current_user, 0) %></td>
                              <td><%= average_of_commitments_by_team(current_user.teams, 0) %></td>
                            <td><%= deviation_percentage(commitments_by(current_user, 0), average_of_commitments_by_team(current_user.teams, 0)) %> % </td>
                            </tr>
                            <tr>
                              <th scope="row">Waiting</th>
                              <td><%= commitments_by(current_user, 1) %></td>
                              <td><%= average_of_commitments_by_team(current_user.teams, 1) %></td>
                              <td><%= deviation_percentage(commitments_by(current_user, 1), average_of_commitments_by_team(current_user.teams, 1)) %> % </td>
                            </tr>
                            <tr>
                              <th scope="row">This Week</th>
                              <td><%= commitments_by(current_user, 2) %></td>
                              <td><%= average_of_commitments_by_team(current_user.teams, 2) %></td>
                              <td><%= deviation_percentage(commitments_by(current_user, 2), average_of_commitments_by_team(current_user.teams, 2)) %> % </td>
                            </tr>
                          </tbody>
                        </table>
                    </div>
                  </div>
                </div>
                <div class="col-sm">
                  <div class="card card-kanban">
                    <div class="card-body">
                      <div class="card-title">
                        <a href="#" data-toggle="modal" data-target="#task-modal">
                          <h6>Mini kanban Board</h6>
                        </a>
                      </div>

                    </div>
                  </div>
                </div>
                <%= timeline [["Washington", 1789-04-29, 1797-03-03], ["Adams", 1797-03-03, 1801-03-03], ["Jefferson", 1801-03-03, 1809-03-03]] %>
                <%= column_chart  [["Backlog", commitments_by(current_user,0)],["Waiting", commitments_by(current_user,1)], ["This Week", commitments_by(current_user,2)], ["Today", commitments_by(current_user,3)], ["Done", commitments_by(current_user,4)] ]  %>
              </div>
            </div>
            <div class="tab-pane fade show <%= @tab == "do" ? "active" : "" %>" id="do" role="tabpanel" aria-labelledby="do-tab" data-filter-list="content-list-body">
              <p>HOLA</p>
            </div>
          </div>
        </div>
      </div>

      <button class="btn btn-primary btn-round btn-floating btn-lg" type="button" data-toggle="collapse" data-target="#floating-chat" aria-expanded="false" aria-controls="sidebar-floating-chat">
        <i class="material-icons">chat_bubble</i>
        <i class="material-icons">close</i>
      </button>


    </div>
  </div>