config/routes.rb
Rails.application.routes.draw do

  namespace :pages do
    get 'obeya_skills'
    get 'index'
    get 'prices'
    get 'evolution'
    get 'competition'
    get 'obeya_global'
    get 'prototipe'

  end

  resources :teams do
    resources :targets, controller: 'teams/targets' do
      resources :problems, only: [:create], controller: 'teams/targets/problems'
      resources :commitments, only: [:create, :show], controller: 'teams/targets/commitments'
    end
  end

  resources :targets
  resources :problems

  resources :commitments do
    resources :tasks, only: [:new, :create, :destroy, :update], controller: 'commitments/tasks'
    member do
      patch :complete
    end
  end

  resources :tasks, only: [] do
    member do
      patch :done
    end
  end

  namespace :charts do
    get 'commitment-level'
    get 'commitment-status'
    get 'planning-level'
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'
      }


  root to: 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commitment.rb
class Commitment < ApplicationRecord
  belongs_to :user
  belongs_to :responsible, class_name: 'User'
  belongs_to :target, optional: true
  has_many :tasks
  has_many_attached :documents
  enum status: [:backlog, :waiting, :this_week, :today, :expired, :closed_before_deadline, :closed_after_deadline]

end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commitment, except: [:create, :nested_create, :index]
  include CommitmentsHelper

  def index
    @commitment = Commitment.new
    @users = User.all
    @tab = params[:tab]
  end

  def create
    @commitment = Commitment.new(commitment_params)
    @commitment.user = current_user
    @commitment.start_date = Date.today
    @commitment.responsible = User.find(params[:commitment][:responsible_id].to_i)
    set_status(@commitment)
    respond_to do |format|
      if @commitment.save
        format.html { redirect_to teams_url(tab: "commitments"), notice: 'Commitment was successfully created'}
        format.json { render json: @commitment, status: :created, location: @commitment }
      else
        format.html { redirect_to teams_url(tab: "commitments"), alert: 'Unprocessable entity'}
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end



  def complete
    @commitment.update_attribute(:closing_date, Date.today)
    byebug
    @commitment.update_attribute(:status, return_status(@commitment))
    redirect_to target_path(@commitment.target_id), notice: 'Commitment completed'
  end

  def show
    @task = Task.new
  end

  def edit
  end

  def update
    @commitment.status = set_status(@commitment)
    @commitment.update(commitment_params)
    redirect_to teams_url(tab: "commitments")
  end

  def destroy
    @commitment.destroy
  end

  private

  def set_commitment
    @commitment = Commitment.find(params[:id])
  end

  def commitment_params
    params.require(:commitment).permit(:action, :conditions_of_satisfaction, :start_date, :due_date, :target_id, :responsible_id , :deliverable, :critical, :renegotiation_date, documents: [])
  end

end

app/controllers/teams/targets/commitments_controller.rb
class Teams::Targets::CommitmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commitment, except: [:create, :nested_create, :index]
  include CommitmentsHelper

  def create
    @commitment = Commitment.new(commitment_params)
    @commitment.user = current_user
    @commitment.start_date = Date.today
    @commitment.responsible = User.find(params[:commitment][:responsible_id].to_i)
    @commitment.target = Target.find(params[:target_id])
    byebug
    set_status(@commitment)
    respond_to do |format|
      if @commitment.save
        format.html { redirect_to team_target_path(Team.find(@commitment.target.team_id), @commitment.target, @commitment), notice: 'Commitment was successfully created'}
        format.json { render json: @commitment, status: :created, location: @commitment }
      else
        format.html { redirect_to teams_url(tab: "commitments"), alert: 'Unprocessable entity'}
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @commitment.update_attribute(:closing_date, Date.today)
    byebug
    @commitment.update_attribute(:status, return_status(@commitment))
    redirect_to target_path(@commitment.target_id), notice: 'Commitment completed'
  end

  def show
    @users = User.all
    @task = Task.new
  end

  def edit
  end

  def update
    update_status(@commitment)
    @commitment.update(commitment_params)
    redirect_to teams_url(tab: "commitments")
  end

  def destroy
    @commitment.destroy
  end

  private
  def update_status

  end

  def set_commitment
    @commitment = Commitment.find(params[:id])
  end

  def commitment_params
    params.require(:commitment).permit(:action, :conditions_of_satisfaction, :start_date, :due_date, :target_id, :responsible_id , :deliverable, :critical, :renegotiation_date, documents: [])
  end
end

app/helpers/commitments_helper.rb
module CommitmentsHelper

  # expected output: number of commitments by object(user, target or team)
  def commitments_by(object, status)
    commitments = []
    if object.is_a?(User)
      commitments = object.owner_commitments.where(status: status).count
    elsif object.is_a?(Target)
      commitments = object.commitments.where(status: status).count
    elsif object.is_a?(Team)
      array = []
      object.targets.each do |target|
        array << target.commitments.where(status: status).count
      end
      commitments = array.inject(0){|sum, x| sum + x }.to_f/array.length if array.length.zero? == false
    end
    commitments != 0 ? commitments: 0
  end

  # expected output: average of commitments by teams
  def average_of_commitments_by_team(teams, status)
    array = []
    teams.each do |team|
      team.targets.each do |target|
        array << target.commitments.where(status: status).count
      end
    end
    commitments = array.inject(0){|sum, x| sum + x }.to_f/array.length if array.length.zero? == false
  end

  # expected output: array of commitments by object(user, target or team)
  def array_of_commitments_by(object, status)
    commitments = []
    if object.is_a?(User)
      commitments = object.owner_commitments.where(status: status)
    elsif object.is_a?(Target)
      commitments = object.commitments.where(status: status)
    elsif object.is_a?(Team)
      array = []
      object.targets.each do |target|
        array << target.commitments.where(status: status)
      end
      commitments = array
    end
    return commitments
  end

  def deviation_percentage(number_one, number_two)
    number_one = number_one.to_f
    number_two = number_two.to_f
    number_one >= 0 ? ((number_one/(number_one - number_two))*100).round(1) : 0
  end

  def deviation_in_numbers(number_one, number_two)
    number_one = number_one.to_f
    number_two = number_two.to_f
    (number_one - number_two)
  end

  def planned_commitments_chart_by(object, acceptable_planning)
    if object.is_a?(User)
      object.owner_commitments.where('(due_date - start_date > ? )', acceptable_planning)
    elsif object.is_a?(Team)
      array = []
      object.targets.each do |target|
        array << target.commitments.where('(due_date - start_date > ? )', acceptable_planning)
      end
      array
    elsif object.is_a?(Target)
      object.commitments.where('(due_date - start_date > ? )', acceptable_planning)
    end
  end


  def bg_targets(target)
    if target_progress(target) < 30
      "bg-danger"
    elsif target_progress(target) >= 30 && target_progress(target) < 80
      "bg-warning"
    else
      "bg-success"
    end
  end


  def self.closing_after_complete(commitment)
    closed_after_deadline(commitment) ? true : false
  end

  def commitment_closed_in_term?(commitment)
    due_date = commitment.due_date
    renegotiation_date = commitment.renegotiation_date
    closing_date = commitment.closing_date
    if closing_date > due_date || closing_date > renegotiation_date
      commitment.closed_in_term = false
    else
      commitment.closed_in_term = true
    end
  end

  def owner_commitment(commitment)
    User.find(commitment).first_name
  end

  def user_id_for_commitment(commitment)
    User.find(commitment.to_i).id
  end


  def backlog_commitments(target)
      target.commitments.where(status: 0)
  end

  def waiting_commitments(target)
    target.commitments.where(status: 1)
  end

  def this_week_commitments(target)
      target.commitments.where(status: 2)
  end

  def today_commitments(target)
      target.commitments.where(status: 3)
  end

  def expired_commitments(target)
      target.commitments.where(status: 4)
  end

  def closed_before_deadline_commitments(target)
      target.commitments.where(status: 5)
  end

  def closed_after_deadline_commitments(target)
      target.commitments.where(status: 6)
  end


  def commitments_closed_in_term(user)
    user.owner_commitments.where(closed_in_term: true)
  end

  # Obeya Skills

  def level_of_commitment(user)
    user.owner_commitments.count == 0 ? 0 : ((user.owner_commitments.where(closed_in_term: true).count.to_f/ user.owner_commitments.count)*100).round(2)
  end

  def level_of_planification(user)
    user.owner_commitments.count.to_f == 0 ? 0 : (((user.owner_commitments.where('(due_date - start_date > 7)').count.to_f)/((user.owner_commitments).count.to_f))*100).round(0)
    end
  end

  def level_of_fullfillment(user)
    if user.owner_commitments.count.to_f == 0
      return 0
    else
    (((user.owner_commitments.where.not(closing_date: nil).count.to_f)/((user.owner_commitments).count.to_f))*100).round(0)
    end
  end

  def resolution(object)
    distances = []
    if object.is_a?(User)
      object.owner_commitments.each do |commitment|
        if !last_date(commitment).nil? && closed?(commitment) && (last_date(commitment) > commitment.closing_date)
          distance = (last_date(commitment).day - commitment.closing_date.day)
          distances << distance
        end
      end
      distances.inject{|sum, x| sum + x }.to_f/ distances.size
    end
  end

  # Set status for commitment
  def set_status(commitment)
    if backlog?(commitment)
      commitment.status = 0
    elsif waiting?(commitment)
      commitment.status = 1
    elsif this_week?(commitment)
      commitment.status = 2
    elsif today?(commitment)
      commitment.status = 3
    elsif expired?(commitment)
      commitment.status = 4
    elsif closed_before_deadline?(commitment)
      commitment.status = 5
    elsif closed_after_deadline?(commitment)
      commitment.status = 6
    else
      commitment.status = nil
    end
  end

  def return_status(commitment)
    if backlog?(commitment)
      0
    elsif waiting?(commitment)
      1
    elsif this_week?(commitment)
      2
    elsif today?(commitment)
      3
    elsif expired?(commitment)
      4
    elsif closed_before_deadline?(commitment)
      5
    elsif closed_after_deadline?(commitment)
      6
    end
  end

  def last_date(commitment)
    commitment.renegotiation_date.nil? ? commitment.due_date : commitment.renegotiation_date
  end

  def closed?(commitment)
    commitment.closing_date.nil? ? false : true
  end

  def backlog?(commitment)
    last_date(commitment).nil? && !closed?(commitment)
  end

  def waiting?(commitment)
    if !closed?(commitment)
      last_date(commitment) > Date.today.at_end_of_week
    end
  end

  def this_week?(commitment)
    week_starts = Date.today.at_beginning_of_week
    week_ends = Date.today.at_end_of_week
    if !closed?(commitment) && !today?(commitment)
      last_date(commitment) >= week_starts && last_date(commitment) <= week_ends
    end
  end

  def today?(commitment)
    today = Date.today
    if !closed?(commitment)
      last_date(commitment) == today
    end
  end

  def expired?(commitment)
    today = Date.today
    if closed?(commitment)
      last_date(commitment) > Date.today
    end
  end

  def closed_after_deadline?(commitment)
    if closed?(commitment)
      if last_date(commitment).nil?
        false
      else
        commitment.closing_date > last_date(commitment)
      end
    end
  end

  def closed_before_deadline?(commitment)
    if closed?(commitment)
      if last_date(commitment).nil?
        true
      else
        commitment.closing_date <= last_date(commitment)
      end
    end
  end

app/helpers/teams/targets/commitments_helper.rb
module Teams::Targets::CommitmentsHelper
end

app/views/commitments/_edit.html.erb
<%= form_with model: commitment, class: "modal fade", id: "commitment-edit-modal-#{commitment.id}", tabindex: "-1", role: "dialog", 'aria-labelledby': "commitment-add-modal", 'aria-hidden': "true" do |f| %>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit commitment</h5>
                <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
                    <i class="material-icons">close</i>
                </button>
            </div>
            <!--end of modal head-->
            <ul class="nav nav-tabs nav-fill">
                <li class="nav-item">
                    <a class="nav-link active" id="commitment-add-details-tab-<%= commitment.id %>" data-toggle="tab" href="#commitment-add-details-<%= commitment.id %>" role="tab" aria-controls="commitment-add-details-<%= commitment.id %>" aria-selected="true">Details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="commitment-add-responsable-tab-<%= commitment.id %>" data-toggle="tab" href="#commitment-add-responsable-<%= commitment.id %>" role="tab" aria-controls="commitment-add-responsable-<%= commitment.id %>" aria-selected="false">Responsible</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="commitment-add-team-tab-<%= commitment.id %>" data-toggle="tab" href="#commitment-add-team-<%= commitment.id %>" role="tab" aria-controls="commitment-add-team-<%= commitment.id %>" aria-selected="false">Target</a>
                </li>
            </ul>
            <div class="modal-body">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="commitment-add-details-<%= commitment.id %>" role="tabpanel" aria-labelledby="commitment-add-details-tab-<%= commitment.id %>">
                        <h6>General Details</h6>
                        <div class="form-group row align-items-center">
                            <label class="col-3">Action</label>
                            <%= f.text_field :action, class: "form-control col", placeholder:"Action to do"%>
                        </div>
                        <div class="form-group row">
                            <label class="col-3">Conditions of satisfaction</label>
                            <%= f.text_area :conditions_of_satisfaction, class: "form-control col", placeholder:"Set conditions of satisfaction", rows:'3'%>
                        </div>
                        <hr>
                        <h6>Timeline</h6>
                        <div class="form-group row align-items-center">
                            <label class="col-3">Due Date</label>
                            <%= f.date_field :due_date, class: "form-control col", placeholder:"commitment due"%>
                        </div>
                        <div class="alert alert-warning text-small" role="alert">
                            <span>You can change due dates at any time.</span>
                        </div>
                        <hr>
                        <h6>Others</h6>
                        <div class="row">
                            <div class="col">
                              <div class="custom-control custom-radio">
                                  <%= f.check_box :deliverable, {checked: (commitment.deliverable == true ? true : false ), class:'custom-control-input', id:"deliverable-option-#{commitment.id}"}, nil %>
                                  <label class="custom-control-label" for="deliverable-option-<%= commitment.id%>">Deliverable</label>
                              </div>
                            </div>
                            <div class="col">
                              <div class="custom-control custom-radio">
                                  <%= f.check_box :critical, {checked: (commitment.critical == true ? true : false ), class:'custom-control-input', id:"critical-option-#{commitment.id}"}, nil %>
                                  <label class="custom-control-label" for="critical-option-<%= commitment.id%>">Critical</label>
                              </div>
                            </div>
                        </div>
                    </div>
                    <!-- start of tabpane responsable -->
                      <div class="tab-pane fade" id="commitment-add-responsable-<%= commitment.id %>" role="tabpanel" aria-labelledby="commitment-add-responsable-tab-<%= commitment.id %>">
                        <div class="users-manage" data-filter-list="form-group-users">
                            <div class="input-group input-group-round">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">filter_list</i>
                                    </span>
                                </div>
                                <input type="search" class="form-control filter-list-input" placeholder="Filter members" aria-label="Filter Members" aria-describedby="filter-members">
                            </div>
                            <div class="form-group-users">
                              <% @users.each do |user| %>
                              <div class="custom-control custom-radio">
                                <%= f.radio_button :responsible_id , user.id, id:"responsible-edit-commitment-#{user.id}", class:'custom-control-input' %>
                                <label class="custom-control-label" for="responsible-edit-commitment-<%= user.id %>">
                                  <div class="d-flex align-items-center">
                                    <%= image_tag user_avatar(user.id), class:'avatar mr-2', 'data-title' => user.first_name , 'data-toggle':'tooltip' %>
                                    <span class="h6 mb-0" data-filter-by="text"><%= user.first_name %> <%= user.last_name %></span>
                                  </div>
                                </label>
                              </div>
                              <% end %>
                            </div>
                        </div>
                    </div>
                    <!-- end of tabpane responsable -->
                    <!-- start of tabpane team -->
                    <div class="tab-pane fade" id="commitment-add-team-<%= commitment.id %>" role="tabpanel" aria-labelledby="commitment-add-team-tab-<%= commitment.id %>">
                        <div class="users-manage" data-filter-list="form-group-users">
                            <div class="mb-3">
                                <ul class="avatars text-center">
                                  Team:
                                    <li>

                                    </li>
                                </ul>
                            </div>
                            <div class="input-group input-group-round">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="material-icons">filter_list</i>
                                    </span>
                                </div>
                                <input type="search" class="form-control filter-list-input" placeholder="Filter members" aria-label="Filter Members" aria-describedby="filter-members">
                            </div>
                            <div class="form-group-users">
                              <% current_user.targets.each do |target| %>
                                <div class="custom-control custom-radio">
                                  <%= f.radio_button :target_id, target.id, id:"target-edit-commitment-#{target.id}", class:'custom-control-input' %>
                                    <label class="custom-control-label" for="target-edit-commitment-<%= target.id %>">
                                        <div class="d-flex align-items-center">
                                            <span class="h6 mb-0" data-filter-by="text"><%= target.title %></span>
                                        </div>
                                    </label>
                                </div>
                            <% end %>
                            </div>
                        </div>
                    </div>
                    <!-- end of tabpane team -->
                </div>
            </div>
            <!--end of modal body-->
            <div class="modal-footer">
              <%= f.submit "Create", class:'btn btn-primary' %>
            </div>
        </div>
    </div>
<% end %>

app/views/commitments/index.html.erb
<div class="layout layout-nav-side">
  <%= render 'shared/navside' %>
  <div class="main-container">
    <div class="navbar bg-white breadcrumb-bar">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="<%= teams_path(tab: '#teams') %>">Overview</a>
          </li>
          <li class="breadcrumb-item active">
            <a> Manager</a>
          </li>

        </ol>
      </nav>

      <div class="dropdown">
        <button class="btn btn-round" role="button" data-toggle="dropdown" aria-expanded="false">
          <i class="material-icons">settings</i>
        </button>
        <div class="dropdown-menu dropdown-menu-right">

          <a class="dropdown-item" href="#">Account Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item text-danger" href="#">Log out</a>

        </div>
      </div>

    </div>
    <%= render 'shared/notices'%>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-11 col-xl-10">
          <div class="page-header mb-4">
            <div class="media">
              <%= image_tag user_avatar(current_user.id), class:'avatar avatar-lg mt-1'%>

              <div class="media-body ml-3">
                <h1 class="mb-0"><%= current_user.first_name %></h1>
                <p class="lead"><%= current_user.bio %></p>
              </div>
            </div>
          </div>
          <ul class="nav nav-tabs nav-fill">
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#my-commitments" role="tab" aria-controls="#my-commitments" aria-selected="false">My commitments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#other-commitments" role="tab" aria-controls="#other-commitments" aria-selected="false">Other Commitments</a>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane fade active show <%= @tab == "my-commitments" ? "active" : "" %>" id="my-commitments" role="tabpanel" aria-labelledby="my-commitments-tab" data-filter-list="content-list-body">

              <!--end of content-list-body-->
            </div>
            <div class="tab-pane fade show <%= @tab == "other-commitments" ? "active" : "" %>" id="other-commitments" role="tabpanel" aria-labelledby="other-commitments-tab" data-filter-list="content-list-body">
              <div class="content-list">
                <div class="row content-list-head">
                  <div class="col-auto">
                    <h3 class="mr-2">Commitments</h3>
                    <%= button_to commitments_path, remote: true, class:'btn btn-round', data: {toggle:'modal', target:'#commitment-add-modal'} do %>
                    <i class="material-icons">add</i>
                    <% end %>
                  </div>
                  <form class="col-md-auto">
                    <div class="input-group input-group-round">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="material-icons">filter_list</i>
                        </span>
                      </div>
                      <input type="search" class="form-control filter-list-input" placeholder="Filter commitments" aria-label="Filter commitments" aria-describedby="filter-commitments">
                    </div>
                  </form>
                </div>


                <div class="card-list-body">
                  <% current_user.responsible_commitments.each do |commitment| %>
                  <div class="card card-task">
                    <div class="progress" >
                        <div id="task-progress" class="progress-bar bg-success" style="width: <%= task_progress(commitment)%>%"></div>
                    </div>
                    <div class="card-body">

                      <div class="card-title">
                        <a href="<%= commitment_path(commitment)%>">
                          <h6 data-filter-by="text"><%= commitment.action %></h6>
                        </a>
                        <% if commitment.target.nil? %>
                        <a href="#">Add a target</a>
                        <% else %>
                        <span class="text-small">Target: <%= commitment.target.title %> / <%= distance_of_time_in_words(commitment.due_date, Time.now) if commitment.due_date.nil? == false %> </span>
                        <% end %>
                      </div>
                      <div class="card-meta">
                        <ul class="avatars">
                          <li>
                            <%= link_to('Done', complete_commitment_path(commitment.id), method: :PATCH, class:'btn btn-sm btn-success') if commitment.closing_date.nil? %>
                            <%= link_to('Renegociate', '#', class:'btn btn-sm btn-primary', data: {toggle:'modal', target:"#commitment-edit-renegociate-date-modal-#{commitment.id}"}) if commitment.renegotiation_date.nil? &&  commitment.closing_date.nil? %>
                          </li>
                        </ul>
                        <ul class="avatars">
                          <li>
                            <a href="#" data-toggle="tooltip" title="<%= owner_commitment(commitment.user_id)%>">
                              <%= image_tag user_avatar(current_user.id), class:'avatar' %>
                            </a>
                          </li>
                        </ul>
                        <div class="d-flex align-items-center">
                          <i class="material-icons">playlist_add_check</i>
                          <span><%= tasks_done(commitment)%>/<%= commitment.tasks.count %></span>
                        </div>
                        <div class="dropdown card-options">
                          <button class="btn-options" type="button" id="task-dropdown-button-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                          </button>
                          <div class="dropdown-menu dropdown-menu-right">
                            <%= link_to 'Edit', '#', class:'dropdown-item', data: {toggle:'modal', target:"#commitment-edit-modal-#{commitment.id}"} %>
                            <%= link_to 'Done', complete_commitment_path(commitment.id), method: :PATCH, class:'dropdown-item' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'Delete', commitment_path(commitment.id), method: :DELETE, class:'dropdown-item text-danger' %>

                          </div>
                        </div>
                      </div>
                    </div>
                    <%= render partial: 'commitments/edit', locals: { commitment: commitment } %>
                    <%= render partial: 'commitments/renegociate', locals: { commitment: commitment } %>
                  </div>
                  <% end %>
                  <%= render 'commitments/new' %>
                </div>

                <!--end of content list body-->
              </div>
              <!--end of content list-->
            </div>
          </div>
        </div>
      </div>

      <button class="btn btn-primary btn-round btn-floating btn-lg" type="button" data-toggle="collapse" data-target="#floating-chat" aria-expanded="false" aria-controls="sidebar-floating-chat">
        <i class="material-icons">chat_bubble</i>
        <i class="material-icons">close</i>
      </button>


    </div>
  </div>